"use client";

import { useState } from "react";
import Link from "next/link";
import { Brain, CheckCircle2, Clock3, ExternalLink, HeartPulse, Search, ShieldAlert, Sparkles, WandSparkles } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Drawer } from "@/components/ui/drawer";
import { StatusPill } from "@/components/ui/status-pill";
import { FailureCategoryChart } from "@/components/operational/charts";
import { failureAnalysisRecords, failureInvestigation, type FailureAnalysisRecord } from "@/lib/mock-data";
import { ActivityIcon } from "@/lib/icons";
import { cn } from "@/lib/utils";

export default function FailureAnalysisPage() {
  const [selected, setSelected] = useState<FailureAnalysisRecord | null>(failureAnalysisRecords[0]);
  const selfHealed = failureAnalysisRecords.filter((item) => item.status === "Self-healed").length;
  const openDefects = failureAnalysisRecords.filter((item) => item.status === "Open defect").length;
  const avgConfidence = Math.round(failureAnalysisRecords.reduce((sum, item) => sum + item.confidence, 0) / failureAnalysisRecords.length);

  return <div className="space-y-6">
    <PageHeader title="Failure Analysis" description="AI-driven root cause analysis, evidence correlation, healing confidence, and remediation tracking." icon={<Brain className="size-5" />} actions={<><Button variant="secondary" asChild><Link href="/execution"><Search className="size-4" /> Execution Grid</Link></Button><Button variant="gradient"><WandSparkles className="size-4" /> Analyze All Failures</Button></>} />

    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric icon={ShieldAlert} label="Failures analyzed" value={failureAnalysisRecords.length.toString()} detail="Latest regression window" accent="text-danger" /><Metric icon={HeartPulse} label="Self-healed" value={`${selfHealed} / ${failureAnalysisRecords.length}`} detail="Locator or data fixes applied" accent="text-success" /><Metric icon={ExternalLink} label="Open defects" value={openDefects.toString()} detail="Escalation still required" accent="text-warning" /><Metric icon={Brain} label="AI confidence" value={`${avgConfidence}%`} detail="Average root-cause confidence" accent="text-primary" /></div>

    <div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle className="text-base">Failure Root-Cause Distribution</CardTitle><CardDescription>Classified by AI evidence across current and recent executions.</CardDescription></CardHeader><CardContent><FailureCategoryChart /></CardContent></Card><Card className="border-primary/25 bg-primary/5"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Sparkles className="size-4 text-primary" /> AI Triage Summary</CardTitle></CardHeader><CardContent className="space-y-3"><Summary label="Highest risk" value="Checkout UI change" tone="text-danger" /><Summary label="Fastest remediation" value="Role locator replacement" tone="text-success" /><Summary label="Data health concern" value="TD-004 catalog fixture stale" tone="text-warning" /><Summary label="Recommended next action" value="Resolve BUG-103 before release" tone="text-primary" /></CardContent></Card></div>

    <Card><CardHeader><CardTitle className="text-base">Failure Investigation Queue</CardTitle><CardDescription>Select a record to inspect evidence, root cause, affected coverage, and suggested remediation.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto scrollbar-thin"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase tracking-wide text-muted-foreground"><th className="px-5 py-3 font-medium">Failure</th><th className="px-5 py-3 font-medium">Category</th><th className="px-5 py-3 font-medium">Severity</th><th className="px-5 py-3 font-medium">AI confidence</th><th className="px-5 py-3 font-medium">Affected tests</th><th className="px-5 py-3 font-medium">Status</th></tr></thead><tbody>{failureAnalysisRecords.map((record) => <tr key={record.id} onClick={() => setSelected(record)} className="cursor-pointer border-b border-border/60 last:border-0 hover:bg-accent/40"><td className="px-5 py-3"><p className="font-mono text-xs text-primary">{record.id} · {record.testId}</p><p className="mt-0.5 font-medium">{record.test}</p><p className="text-xs text-muted-foreground">{record.occurredAt} · {record.duration}</p></td><td className="px-5 py-3"><Badge variant="secondary">{record.category}</Badge></td><td className="px-5 py-3"><StatusPill status={record.severity} /></td><td className="px-5 py-3"><div className="flex items-center gap-2"><div className="h-1.5 w-16 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${record.confidence}%` }} /></div><span className="text-xs font-medium">{record.confidence}%</span></div></td><td className="px-5 py-3 tabular-nums">{record.affectedTests}</td><td className="px-5 py-3"><StatusPill status={record.status} /></td></tr>)}</tbody></table></div></CardContent></Card>

    <Drawer open={!!selected} onClose={() => setSelected(null)}>{selected && <FailureDrawer record={selected} />}</Drawer>
  </div>;
}

function FailureDrawer({ record }: { record: FailureAnalysisRecord }) { return <div className="p-6"><div className="flex items-center gap-2 text-primary"><Sparkles className="size-4" /><span className="text-sm font-medium">AI Failure Investigation</span></div><span className="mt-3 block font-mono text-xs text-primary">{record.id} · {record.testId}</span><h2 className="mt-1 text-xl font-semibold">{record.test}</h2><div className="mt-3 flex flex-wrap gap-2"><StatusPill status={record.severity} /><Badge variant="secondary">{record.category}</Badge><StatusPill status={record.status} /></div>
  <section className="mt-6"><h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Root cause</h3><p className="mt-2 rounded-lg border border-danger/30 bg-danger/5 p-3 text-sm">{record.rootCause}</p></section><section className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Suggested remediation</h3><p className="mt-2 rounded-lg border border-success/30 bg-success/5 p-3 text-sm">{record.suggestedFix}</p></section>
  <section className="mt-6"><h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Evidence</h3><div className="flex flex-wrap gap-2">{record.evidence.map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div></section><section className="mt-6"><h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">AI investigation timeline</h3><div className="space-y-1">{failureInvestigation.map((step, index) => <div key={step.label} className="relative pl-9">{index !== failureInvestigation.length - 1 && <span className="absolute left-[15px] top-8 h-[calc(100%-0.5rem)] w-px bg-border" />}<div className={cn("absolute left-0 top-1 flex size-8 items-center justify-center rounded-full border", index === failureInvestigation.length - 1 ? "border-success/40 bg-success/10 text-success" : "border-primary/30 bg-primary/10 text-primary")}><ActivityIcon name={step.icon} className="size-4" /></div><div className="pb-4"><p className="text-sm font-medium">{step.label}</p><p className="text-xs text-muted-foreground">{step.detail}</p></div></div>)}</div></section><div className="mt-5 grid grid-cols-2 gap-2"><Button variant="gradient"><HeartPulse className="size-4" /> Apply Suggested Fix</Button><Button variant="secondary"><ExternalLink className="size-4" /> Create / Open Defect</Button></div></div>; }
function Metric({ icon: Icon, label, value, detail, accent }: { icon: typeof Brain; label: string; value: string; detail: string; accent: string }) { return <Card><CardContent className="p-5"><Icon className={cn("size-5", accent)} /><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>; }
function Summary({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-lg border border-border bg-card/60 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className={cn("mt-1 text-sm font-medium", tone)}>{value}</p></div>; }
